BaseURL = "192.168.1.1"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Your Blog Title"
Theme = "fancy"
pygmentsStyle = "default"
pygmentsUseClasses = true
copyright = "Copyright (c) 2020. All rights reserved. 苏ICP备1111111号-2"

[Author]
  Name = "YourName"

[outputs]
  home = [ "RSS", "HTML" ]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  Author = "YourName"
  AuthorHomepage = "yourhome.com"
  BottomIntroduce = "introduce1<br/> introduce2"
  Description = "Your Description"
  Subtitle = "Your subtitle"
  Weibo = "YourWeb"
  WeiboID = 0000000
  Twitter = "yourtwitter"
  Zhihu = "yourzhihu"
  GitHub = "yourgithub"
  Facebook = "yourfacebook"
  LinkIn = "yourlink"
  Imglogo = "img/fancy.jpg"
  AuthorImg = "img/fancy.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = ""

  [Params.Disqus]
    ShortName = "yourname"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2

